return {
    lsp = {
        "bashls",
        "clangd",
        -- "csharp_ls",
        "cmake",
        "cssls",
        -- "denols",
        "dockerls",
        "docker_compose_language_service",
        "golangci_lint_ls",
        "gopls",
        "graphql",
        "html",
        "jsonls",
        "ts_ls",
        "lua_ls",
        "rust_analyzer",
        "sqlls",
        "taplo",
        "lemminx",
        "yamlls",
        "pylsp",
        -- "tofu_ls",
        "terraformls",
        "buf_ls",
    },
    dap = {
        "codelldb",
        "js-debug-adapter",
        "delve",
    },
    null_ls = {},
}
