local colors = {
-- PATCH_OPEN
Normal = {fg = "#4B4E68", bg = "#EFF1F5"},
DiffviewNormal = {link = "Normal"},
NormalNC = {link = "Normal"},
NormalSB = {link = "Normal"},
TabLineSel = {link = "Normal"},
Backdrop = {fg = "#000000", bg = "#000000", blend = 70},
BinkCmpKindCopilot = {fg = "#E6E9EF", bg = "#17959B", bold = true},
BlinkCmpKind = {fg = "#1F66F4"},
BlinkCmpKindClass = {fg = "#E6E9EF", bg = "#DD8D1D", bold = true},
BlinkCmpKindColor = {fg = "#E6E9EF", bg = "#D20F39", bold = true},
BlinkCmpKindConstant = {fg = "#E6E9EF", bg = "#FE640B", bold = true},
BlinkCmpKindConstructor = {fg = "#E6E9EF", bg = "#1F66F4", bold = true},
BlinkCmpKindEnum = {fg = "#E6E9EF", bg = "#DD8D1D", bold = true},
BlinkCmpKindEnumMember = {fg = "#E6E9EF", bg = "#17959B", bold = true},
BlinkCmpKindEvent = {fg = "#E6E9EF", bg = "#1F66F4", bold = true},
BlinkCmpKindField = {fg = "#E6E9EF", bg = "#41A12B", bold = true},
BlinkCmpKindFile = {fg = "#E6E9EF", bg = "#1F66F4", bold = true},
BlinkCmpKindFolder = {fg = "#E6E9EF", bg = "#1F66F4", bold = true},
BlinkCmpKindFunction = {fg = "#E6E9EF", bg = "#1F66F4", bold = true},
BlinkCmpKindInterface = {fg = "#E6E9EF", bg = "#DD8D1D", bold = true},
BlinkCmpKindKeyword = {fg = "#E6E9EF", bg = "#8839EF", bold = true},
BlinkCmpKindMethod = {fg = "#E6E9EF", bg = "#1F66F4", bold = true},
BlinkCmpKindModule = {fg = "#E6E9EF", bg = "#1F66F4", bold = true},
BlinkCmpKindOperator = {fg = "#E6E9EF", bg = "#04A7E7", bold = true},
BlinkCmpKindProperty = {fg = "#E6E9EF", bg = "#1F66F4", bold = true},
BlinkCmpKindReference = {fg = "#E6E9EF", bg = "#D20F39", bold = true},
BlinkCmpKindSnippet = {fg = "#E6E9EF", bg = "#DD7878", bold = true},
BlinkCmpKindStruct = {fg = "#E6E9EF", bg = "#1F66F4", bold = true},
BlinkCmpKindText = {fg = "#E6E9EF", bg = "#41A12B", bold = true},
BlinkCmpKindTypeParameter = {fg = "#E6E9EF", bg = "#E64754", bold = true},
BlinkCmpKindUnit = {fg = "#E6E9EF", bg = "#41A12B", bold = true},
BlinkCmpKindValue = {fg = "#E6E9EF", bg = "#FE640B", bold = true},
BlinkCmpKindVariable = {fg = "#E6E9EF", bg = "#DD7878", bold = true},
BlinkCmpLabel = {fg = "#7B7E93"},
BlinkCmpLabelDeprecated = {fg = "#9CA0B0", strikethrough = true},
BlinkCmpMenuSelection = {bg = "#CDD1DB", bold = true},
BlinkCmpScrollBarGutter = {bg = "#BCC0CD"},
BlinkCmpScrollBarThumb = {bg = "#9CA0B0"},
Bold = {bold = true},
NeogitPopupBold = {link = "Bold"},
Boolean = {fg = "#FE640B"},
["@boolean"] = {link = "Boolean"},
Character = {fg = "#17959B"},
["@character"] = {link = "Character"},
ColorColumn = {bg = "#CDD1DB"},
Comment = {fg = "#7B7E93"},
DiffviewDim1 = {link = "Comment"},
DiffviewFilePanelPath = {link = "Comment"},
GitSignsCurrentLineBlame = {link = "Comment"},
NeogitObjectId = {link = "Comment"},
NeogitRebaseDone = {link = "Comment"},
NeogitStash = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@comment.documentation"] = {link = "Comment"},
["@comment.error"] = {link = "Comment"},
["@comment.note"] = {link = "Comment"},
["@comment.todo"] = {link = "Comment"},
["@comment.warning"] = {link = "Comment"},
ComplHint = {fg = "#6C6F84"},
Conceal = {fg = "#8C8FA1"},
Conditional = {fg = "#8839EF"},
Constant = {fg = "#FE640B"},
["@constant"] = {link = "Constant"},
["@constant.builtin"] = {link = "Constant"},
["@constant.macro"] = {link = "Constant"},
CurSearch = {fg = "#E6E9EF", bg = "#D20F39"},
Cursor = {fg = "#BCC0CD", bg = "#8839EF"},
CursorIM = {link = "Cursor"},
TermCursor = {link = "Cursor"},
lCursor = {link = "Cursor"},
CursorColumn = {bg = "#E6E9EF"},
CursorLine = {bg = "#CDD5E5"},
OverseerCursorLine = {link = "CursorLine"},
CursorLineFold = {},
CursorLineNr = {fg = "#7287FD"},
CursorLineSign = {},
DapBreakpoint = {fg = "#D20F39"},
DapBreakpointCondition = {fg = "#DD8D1D"},
DapBreakpointRejected = {fg = "#8839EF"},
DapLogPoint = {fg = "#04A7E7"},
DapStopped = {fg = "#E64754"},
DapUIBreakpointsCurrentLine = {fg = "#41A12B", bold = true},
DapUIBreakpointsDisabledLine = {fg = "#ACB0BE"},
DapUIBreakpointsInfo = {fg = "#41A12B"},
DapUIBreakpointsPath = {fg = "#04A7E7"},
DapUIDecoration = {fg = "#04A7E7"},
DapUILineNumber = {fg = "#04A7E7"},
DapUIModifiedValue = {fg = "#FE640B"},
DapUIPlayPause = {fg = "#41A12B"},
DapUIPlayPauseNC = {link = "DapUIPlayPause"},
DapUIRestart = {fg = "#41A12B"},
DapUIRestartNC = {link = "DapUIRestart"},
DapUIScope = {fg = "#04A7E7"},
DapUISource = {fg = "#7287FD"},
DapUIStepBack = {fg = "#1F66F4"},
DapUIStepBackNC = {link = "DapUIStepBack"},
DapUIStepInto = {fg = "#1F66F4"},
DapUIStepInfoNC = {link = "DapUIStepInto"},
DapUIStepOut = {fg = "#1F66F4"},
DapUIStepOutNC = {link = "DapUIStepOut"},
DapUIStepOver = {fg = "#1F66F4"},
DapUIStepOverNC = {link = "DapUIStepOver"},
DapUIStop = {fg = "#D20F39"},
DapUIStopNC = {link = "DapUIStop"},
DapUIStoppedThread = {fg = "#04A7E7"},
DapUIThread = {fg = "#41A12B"},
DapUIType = {fg = "#8839EF"},
DapUIUnavailable = {fg = "#BCC0CD"},
DapUIUnavailableNC = {link = "DapUIUnavailable"},
DapUIValue = {fg = "#04A7E7"},
DapUIVariable = {fg = "#4B4E68"},
DapUIWatchesEmpty = {fg = "#E64754"},
DapUIWatchesError = {fg = "#E64754"},
DapUIWatchesValue = {fg = "#41A12B"},
DapUIWinSelect = {fg = "#FE640B"},
Delimiter = {fg = "#7B7E93"},
["@punctuation.bracket"] = {link = "Delimiter"},
["@punctuation.delimiter"] = {link = "Delimiter"},
DiagnosticError = {fg = "#D20F39"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
LspDiagnosticsDefaultError = {link = "DiagnosticError"},
NeogitNotificationError = {link = "DiagnosticError"},
NeotestFailed = {link = "DiagnosticError"},
OverseerFAILURE = {link = "DiagnosticError"},
LspDiagnosticsFloatingError = {link = "DiagnosticFloatingError"},
LspDiagnosticsFloatingHint = {link = "DiagnosticFloatingHint"},
LspDiagnosticsFloatingInformation = {link = "DiagnosticFloatingInfo"},
LspDiagnosticsFloatingWarning = {link = "DiagnosticFloatingWarn"},
DiagnosticHint = {fg = "#17959B"},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticSignHint = {link = "DiagnosticHint"},
LspDiagnosticsDefaultHint = {link = "DiagnosticHint"},
DiagnosticInfo = {fg = "#04A7E7"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
LspDiagnosticsDefaultInformation = {link = "DiagnosticInfo"},
NeogitNotificationInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "#41A12B"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
NeotestPassed = {link = "DiagnosticOk"},
OverseerSUCCESS = {link = "DiagnosticOk"},
DiagnosticUnderlineError = {sp = "#D20F39", underline = true},
LspDiagnosticsUnderlineError = {link = "DiagnosticUnderlineError"},
DiagnosticUnderlineHint = {sp = "#17959B", underline = true},
LspDiagnosticsUnderlineHint = {link = "DiagnosticUnderlineHint"},
DiagnosticUnderlineInfo = {sp = "#04A7E7", underline = true},
LspDiagnosticsUnderlineInformation = {link = "DiagnosticUnderlineInfo"},
DiagnosticUnderlineOk = {sp = "#41A12B", underline = true},
DiagnosticUnderlineWarn = {sp = "#DD8D1D", underline = true},
LspDiagnosticsUnderlineWarning = {link = "DiagnosticUnderlineWarn"},
DiagnosticVirtualTextError = {fg = "#D20F39", bg = "#D7C1D3"},
LspDiagnosticsVirtualTextError = {link = "DiagnosticVirtualTextError"},
DiagnosticVirtualTextHint = {fg = "#17959B", bg = "#AFCDD9"},
LspDiagnosticsVirtualTextHint = {link = "DiagnosticVirtualTextHint"},
DiagnosticVirtualTextInfo = {fg = "#04A7E7", bg = "#B6D0E2"},
LspDiagnosticsVirtualTextInformation = {link = "DiagnosticVirtualTextInfo"},
DiagnosticVirtualTextOk = {fg = "#41A12B", bg = "#BFD4CD"},
DiagnosticVirtualTextWarn = {fg = "#DD8D1D", bg = "#D2CECB"},
LspDiagnosticsVirtualTextWarning = {link = "DiagnosticVirtualTextWarn"},
DiagnosticWarn = {fg = "#DD8D1D"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
LspDiagnosticsDefaultWarning = {link = "DiagnosticWarn"},
NeogitNotificationWarning = {link = "DiagnosticWarn"},
DiffAdd = {fg = "#41A12B"},
GitAdded = {link = "DiffAdd"},
["@diff.plus"] = {link = "DiffAdd"},
DiffChange = {fg = "#DD8D1D"},
GitModified = {link = "DiffChange"},
["@diff.delta"] = {link = "DiffChange"},
DiffDelete = {fg = "#D20F39"},
GitDeleted = {link = "DiffDelete"},
["@diff.minus"] = {link = "DiffDelete"},
DiffText = {fg = "#4B4E68"},
DiffviewFilePanelCounter = {fg = "#4B4E68"},
DiffviewFilePanelFileName = {fg = "#4B4E68"},
DiffviewFilePanelRootPath = {fg = "#7287FD", bold = true},
DiffviewFilePanelSelected = {fg = "#DD8D1D"},
DiffviewFilePanelTitle = {fg = "#1F66F4", bold = true},
DiffviewPrimary = {fg = "#1F66F4"},
DiffviewSecondary = {fg = "#41A12B"},
Directory = {fg = "#1F66F4"},
NeoTreeDirectoryName = {link = "Directory"},
NeotestDir = {link = "Directory"},
NeotestFile = {link = "Directory"},
EndOfBuffer = {fg = "#BCC0CD"},
Error = {fg = "#D20F39"},
ErrorMsg = {fg = "#D20F39", bold = true, italic = true},
Exception = {fg = "#8839EF"},
["@number.float"] = {link = "Float"},
FloatBorder = {fg = "#E6E9EF", bg = "#E6E9EF"},
BlinkCmpSignatureHelpBorder = {link = "FloatBorder"},
DapUIFloatBorder = {link = "FloatBorder"},
LspInfoBorder = {link = "FloatBorder"},
NeoTreeFloatBorder = {link = "FloatBorder"},
NoicePopupBorder = {link = "FloatBorder"},
NoicePopupmenuBorder = {link = "FloatBorder"},
TelescopeBorder = {link = "FloatBorder"},
WhichKeyBorder = {link = "FloatBorder"},
FloatShadow = {},
FloatTitle = {fg = "#4B4E68", bg = "#E6E9EF", bold = true},
NeoTreeFloatTitle = {link = "FloatTitle"},
NoicePopupTitle = {link = "FloatTitle"},
TelescopeTitle = {link = "FloatTitle"},
FoldColumn = {fg = "#9CA0B0"},
Folded = {fg = "#1F66F4"},
NeogitFold = {link = "Folded"},
Function = {fg = "#1F66F4"},
DiffviewReference = {link = "Function"},
NeogitUnmergedInto = {link = "Function"},
NeogitUnpulledFrom = {link = "Function"},
NeogitUnpushedTo = {link = "Function"},
OverseerTask = {link = "Function"},
["@constructor"] = {link = "Function"},
["@function"] = {link = "Function"},
["@function.builtin"] = {link = "Function"},
["@function.call"] = {link = "Function"},
["@function.method"] = {link = "Function"},
["@function.method.call"] = {link = "Function"},
DiffviewFilePanelInsertions = {link = "GitAdded"},
DiffviewStatusAdded = {link = "GitAdded"},
GitNew = {link = "GitAdded"},
GitSignsAdd = {link = "GitAdded"},
GitStaged = {link = "GitAdded"},
NeoTreeGitAdded = {link = "GitAdded"},
NeogitDiffAdd = {link = "GitAdded"},
DiffviewFilePanelConflicts = {link = "GitConflict"},
DiffviewStatusBroken = {link = "GitConflict"},
NeoTreeGitConflict = {link = "GitConflict"},
DiffviewStatusCopied = {link = "GitCopied"},
DiffviewFilePanelDeletions = {link = "GitDeleted"},
DiffviewStatusDeleted = {link = "GitDeleted"},
GitConflict = {link = "GitDeleted"},
GitSignsDelete = {link = "GitDeleted"},
GitUnstaged = {link = "GitDeleted"},
NeoTreeGitDeleted = {link = "GitDeleted"},
NeogitDiffDelete = {link = "GitDeleted"},
GitIgnored = {fg = "#9CA0B0"},
DiffviewStatusIgnored = {link = "GitIgnored"},
NeoTreeGitIgnored = {link = "GitIgnored"},
DiffviewStatusModified = {link = "GitModified"},
DiffviewStatusTypeChange = {link = "GitModified"},
GitCopied = {link = "GitModified"},
GitRenamed = {link = "GitModified"},
GitSignsChange = {link = "GitModified"},
GitUpdated = {link = "GitModified"},
NeoTreeGitModified = {link = "GitModified"},
DiffviewStatusRenamed = {link = "GitRenamed"},
GitSignsAddInline = {fg = "#EFF1F5", bg = "#41A12B", bold = true},
GitSignsAddPreview = {fg = "#41A12B", bg = "none"},
GitSignsChangeInline = {fg = "#EFF1F5", bg = "#DD8D1D", bold = true},
GitSignsDeleteInline = {fg = "#EFF1F5", bg = "#D20F39", bold = true},
GitSignsDeletePreview = {fg = "#D20F39", bg = "none"},
NeoTreeGitStaged = {link = "GitStaged"},
DiffviewStatusUnmerged = {link = "GitUnmerged"},
GitUnmerged = {link = "GitUnstaged"},
GitUnpulled = {link = "GitUnstaged"},
NeoTreeGitUnstaged = {link = "GitUnstaged"},
GitUntracked = {fg = "#8839EF"},
DiffviewStatusUntracked = {link = "GitUntracked"},
NeoTreeGitUntracked = {link = "GitUntracked"},
Identifier = {fg = "#DD7878"},
DiffviewHash = {link = "Identifier"},
NeogitBranch = {link = "Identifier"},
OverseerComponent = {link = "Identifier"},
["@module"] = {link = "Identifier"},
["@module.builtin"] = {link = "Identifier"},
Ignore = {},
IncSearch = {fg = "#E6E9EF", bg = "#0386BA"},
Include = {fg = "#8839EF"},
Italic = {italic = true},
Keyword = {fg = "#8839EF"},
["@keyword"] = {link = "Keyword"},
["@keyword.conditional"] = {link = "Keyword"},
["@keyword.conditional.ternary"] = {link = "Keyword"},
["@keyword.coroutine"] = {link = "Keyword"},
["@keyword.debug"] = {link = "Keyword"},
["@keyword.directive"] = {link = "Keyword"},
["@keyword.directive.define"] = {link = "Keyword"},
["@keyword.exception"] = {link = "Keyword"},
["@keyword.function"] = {link = "Keyword"},
["@keyword.import"] = {link = "Keyword"},
["@keyword.modifier"] = {link = "Keyword"},
["@keyword.operator"] = {link = "Keyword"},
["@keyword.repeat"] = {link = "Keyword"},
["@keyword.return"] = {link = "Keyword"},
["@keyword.type"] = {link = "Keyword"},
Label = {fg = "#20A0B6"},
["@label"] = {link = "Label"},
LineNr = {fg = "#BCC0CD"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
LspCodeLens = {fg = "#9CA0B0"},
LspCodeLensSeparator = {link = "LspCodeLens"},
LspDiagnosticsError = {link = "LspDiagnosticsDefaultError"},
LspDiagnosticsHint = {link = "LspDiagnosticsDefaultHint"},
LspDiagnosticsInformation = {link = "LspDiagnosticsDefaultInformation"},
LspDiagnosticsWarning = {link = "LspDiagnosticsDefaultWarning"},
LspInlayHint = {fg = "#9CA0B0"},
LspReferenceText = {bg = "#BCC0CD"},
LspReferenceRead = {link = "LspReferenceText"},
LspReferenceWrite = {link = "LspReferenceText"},
LspSignatureActiveParameter = {bold = true},
["@function.macro"] = {link = "Macro"},
MarkviewBlockQuoteDefault = {fg = "#7B7E93", bg = "#E6E9EF"},
MarkviewBlockQuoteError = {fg = "#D20F39", bg = "#E6E9EF"},
MarkviewBlockQuoteNote = {fg = "#04A7E7", bg = "#E6E9EF"},
MarkviewBlockQuoteOk = {fg = "#41A12B", bg = "#E6E9EF"},
MarkviewBlockQuoteSpecial = {fg = "#EA76CB", bg = "#E6E9EF"},
MarkviewBlockQuoteWarn = {fg = "#DD8D1D", bg = "#E6E9EF"},
MarkviewCode = {bg = "#E6E9EF"},
MarkviewCodeFg = {fg = "#E6E9EF"},
MarkviewCodeInfo = {fg = "#ACB0BE", bg = "#E6E9EF"},
MarkviewIcon = {bg = "#E6E9EF"},
MarkviewIcon0 = {fg = "#7B7E93", bg = "#E6E9EF"},
MarkviewIcon1 = {fg = "#D20F39", bg = "#E6E9EF"},
MarkviewIcon2 = {fg = "#FE640B", bg = "#E6E9EF"},
MarkviewIcon3 = {fg = "#DD8D1D", bg = "#E6E9EF"},
MarkviewIcon4 = {fg = "#41A12B", bg = "#E6E9EF"},
MarkviewIcon5 = {fg = "#20A0B6", bg = "#E6E9EF"},
MarkviewIcon6 = {fg = "#7287FD", bg = "#E6E9EF"},
MarkviewIcon7 = {fg = "#8839EF", bg = "#E6E9EF"},
MarkviewInlineCode = {bg = "#CDD1DB"},
MarkviewPalette0Bg = {bg = "#CDD1DB"},
MarkviewPalette0Fg = {fg = "#7B7E93"},
MarkviewPalette1Bg = {bg = "#CDD1DB"},
MarkviewPalette1Fg = {fg = "#D20F39"},
MarkviewPalette2Bg = {bg = "#CDD1DB"},
MarkviewPalette2Fg = {fg = "#FE640B"},
MarkviewPalette3Bg = {bg = "#CDD1DB"},
MarkviewPalette3Fg = {fg = "#DD8D1D"},
MarkviewPalette4Bg = {bg = "#CDD1DB"},
MarkviewPalette4Fg = {fg = "#41A12B"},
MarkviewPalette5Bg = {bg = "#CDD1DB"},
MarkviewPalette5Fg = {fg = "#20A0B6"},
MarkviewPalette6Bg = {bg = "#CDD1DB"},
MarkviewPalette6Fg = {fg = "#7287FD"},
MarkviewPalette7Bg = {bg = "#CDD1DB"},
MarkviewPalette7Fg = {fg = "#8839EF"},
MarkviewPallete = {bg = "#CDD1DB"},
MarkviewPallete0 = {fg = "#7B7E93", bg = "#CDD1DB"},
MarkviewPallete1 = {fg = "#D20F39", bg = "#CDD1DB"},
MarkviewPallete2 = {fg = "#FE640B", bg = "#CDD1DB"},
MarkviewPallete3 = {fg = "#DD8D1D", bg = "#CDD1DB"},
MarkviewPallete4 = {fg = "#41A12B", bg = "#CDD1DB"},
MarkviewPallete5 = {fg = "#20A0B6", bg = "#CDD1DB"},
MarkviewPallete6 = {fg = "#7287FD", bg = "#CDD1DB"},
MarkviewPallete7 = {fg = "#8839EF", bg = "#CDD1DB"},
MasonError = {fg = "#D20F39"},
MasonHeader = {fg = "#EFF1F5", bg = "#7287FD", bold = true},
MasonHeaderSecondary = {fg = "#EFF1F5", bg = "#1F66F4", bold = true},
MasonHeading = {fg = "#7287FD", bold = true},
MasonHighlight = {fg = "#41A12B"},
MasonHighlightBlock = {fg = "#EFF1F5", bg = "#41A12B"},
MasonHighlightBlockBold = {fg = "#EFF1F5", bg = "#41A12B", bold = true},
MasonHighlightBlockBoldSecondary = {fg = "#EFF1F5", bg = "#8839EF", bold = true},
MasonHighlightBlockSecondary = {fg = "#EFF1F5", bg = "#8839EF"},
MasonHighlightSecondary = {fg = "#8839EF"},
MasonMuted = {fg = "#9CA0B0"},
MasonMutedBlock = {fg = "#EFF1F5", bg = "#9CA0B0"},
MasonMutedBlockBold = {fg = "#EFF1F5", bg = "#9CA0B0", bold = true},
MatchParen = {fg = "#FE640B", bg = "#E0E4EB", bold = true},
ModeMsg = {fg = "#4B4E68", bold = true},
MoreMsg = {fg = "#1F66F4"},
MsgArea = {},
NeoTreeDimText = {fg = "#8C8FA1"},
DiffviewFolderSign = {link = "NeoTreeDirectoryIcon"},
DiffviewFolderName = {link = "NeoTreeDirectoryName"},
NeoTreeDirectoryIcon = {link = "NeoTreeDirectoryName"},
NeoTreeRootName = {link = "NeoTreeDirectoryName"},
NeoTreeExpander = {fg = "#9CA0B0"},
NeoTreeIndentMarker = {link = "NeoTreeExpander"},
NeoTreeFileNameOpened = {fg = "#EA76CB"},
NeoTreeFilterTerm = {fg = "#41A12B", bold = true},
NeoTreeModified = {fg = "#FE640B"},
NeoTreeNormal = {fg = "#4B4E68", bg = "#E6E9EF"},
NeoTreeNormalNC = {link = "NeoTreeNormal"},
NeoTreeStatusLineNC = {fg = "#E6E9EF", bg = "#E6E9EF"},
NeoTreeSymbolicLinkTarget = {fg = "#EA76CB"},
NeoTreeTabActive = {fg = "#7287FD", bg = "#E6E9EF", bold = true},
NeoTreeTabInactive = {fg = "#9CA0B0", bg = "#EFF1F5"},
NeoTreeTabSeparatorActive = {fg = "#E6E9EF", bg = "#E6E9EF", bold = true},
NeoTreeTabSeparatorInactive = {fg = "#EFF1F5", bg = "#EFF1F5"},
NeoTreeTitleBar = {fg = "#4B4E68", bg = "#DDE1E9", bold = true},
NeoTreeVertSplit = {fg = "#EFF1F5", bg = "#EFF1F5"},
NeoTreeWinSeparator = {fg = "#EFF1F5", bg = "#EFF1F5"},
NeogitChangeAdded = {fg = "#41A12B", bold = true},
NeogitChangeBothModified = {fg = "#DD8D1D", bold = true},
NeogitChangeCopied = {fg = "#DD8D1D", bold = true},
NeogitChangeDeleted = {fg = "#D20F39", bold = true},
NeogitChangeModified = {fg = "#DD8D1D", bold = true},
NeogitChangeNewFile = {fg = "#41A12B", bold = true},
NeogitChangeRenamed = {fg = "#DD8D1D", bold = true},
NeogitChangeUpdated = {fg = "#DD8D1D", bold = true},
NeogitDiffAddHighlight = {link = "NeogitDiffAdd"},
NeogitDiffContext = {bg = "#EFF1F5"},
NeogitDiffContextHighlight = {bg = "#CDD1DB"},
NeogitDiffDeleteHighlight = {link = "NeogitDiffDelete"},
NeogitDiffHeaderHighlight = {link = "NeogitDiffHeader"},
NeogitFilePath = {fg = "#1F66F4", italic = true},
NeogitGraphBlue = {fg = "#1F66F4"},
NeogitGraphBoldBlue = {fg = "#1F66F4", bold = true},
NeogitGraphBoldCyan = {fg = "#20A0B6", bold = true},
NeogitGraphBoldGray = {fg = "#5B5E76", bold = true},
NeogitGraphBoldGreen = {fg = "#41A12B", bold = true},
NeogitGraphBoldOrange = {fg = "#FE640B", bold = true},
NeogitGraphBoldPirple = {fg = "#8839EF", bold = true},
NeogitGraphBoldRed = {fg = "#D20F39", bold = true},
NeogitGraphBoldWhite = {fg = "#EFF1F5", bold = true},
NeogitGraphBoldYellow = {fg = "#DD8D1D", bold = true},
NeogitGraphCyan = {fg = "#20A0B6"},
NeogitGraphGray = {fg = "#5B5E76"},
NeogitGraphGreen = {fg = "#41A12B"},
NeogitGraphOrange = {fg = "#FE640B"},
NeogitGraphPirple = {fg = "#8839EF"},
NeogitGraphRed = {fg = "#D20F39"},
NeogitGraphWhite = {fg = "#EFF1F5"},
NeogitGraphYellow = {fg = "#DD8D1D"},
NeogitHunkHeaderHighlight = {link = "NeogitHunkHeader"},
NeogitPopupActionKey = {fg = "#7287FD"},
NeogitPopupConfigKey = {fg = "#7287FD"},
NeogitPopupOptionKey = {fg = "#7287FD"},
NeogitPopupSwitchKey = {fg = "#7287FD"},
NeogitRebasing = {fg = "#8839EF", bold = true},
NeogitRecentcommits = {fg = "#41A12B", bold = true},
NeogitRemote = {fg = "#8839EF", bold = true},
NeogitStagedchanges = {fg = "#41A12B", bold = true},
NeogitStashes = {fg = "#8839EF", bold = true},
NeogitTagDistance = {link = "NeogitTagName"},
NeogitUnmergedchanges = {fg = "#D20F39", bold = true},
NeogitUnpulledchanges = {fg = "#D20F39", bold = true},
NeogitUnstagedchanges = {fg = "#D20F39", bold = true},
NeogitUntrackedfiles = {fg = "#8839EF", bold = true},
NeotestAdapterName = {fg = "#E64754"},
NeotestExpandMarker = {fg = "#8C8FA1"},
NeotestFocused = {bold = true, underline = true},
NeotestIndent = {fg = "#8C8FA1"},
NeotestMarked = {fg = "#FE640B", bold = true},
NeotestNamespace = {fg = "#8839EF"},
NeotestRunning = {fg = "#DD8D1D"},
NeotestSkipped = {fg = "#1F66F4"},
NeotestTarget = {fg = "#D20F39"},
NeotestTest = {fg = "#4B4E68"},
NeotestUnknown = {fg = "#4B4E68"},
NeotestWinSelect = {fg = "#1F66F4", bold = true},
NoiceCmdline = {fg = "#4B4E68", bg = "#CDD1DB"},
NoiceCmdlinePopup = {link = "NoiceCmdline"},
NoiceCmdlineIcon = {fg = "#8839EF"},
NoiceCmdlineIconSearch = {fg = "#DD8D1D"},
NoiceCmdlinePopupBorderSearch = {link = "NoiceCmdlineIconSearch"},
NoiceCmdlinePopupTitle = {link = "NoiceCmdlinePopup"},
NoiceCmdlinePopupBorder = {fg = "#CDD1DB", bg = "#CDD1DB"},
NoiceCmdlinePopupBorderInput = {link = "NoiceCmdlinePopupBorder"},
NoiceCmdlinePopupTitleInput = {link = "NoiceCmdlinePopupTitle"},
NoiceFormatProgressDone = {fg = "#6C6F84"},
NoiceFormatProgressTodo = {fg = "#6C6F84"},
NoiceMini = {fg = "#6C6F84"},
NonText = {fg = "#9CA0B0"},
SpecialKey = {link = "NonText"},
NormalFloat = {fg = "#4B4E68", bg = "#E6E9EF"},
BlinkCmpDoc = {link = "NormalFloat"},
NeogitNormal = {link = "NormalFloat"},
NoicePopup = {link = "NormalFloat"},
NoicePopupmenu = {link = "NormalFloat"},
TelescopeNormal = {link = "NormalFloat"},
WhichKey = {link = "NormalFloat"},
NotifyBody = {fg = "#4B4E68", bg = "#CDD1DB"},
NotifyBorder = {fg = "#CDD1DB", bg = "#CDD1DB"},
NotifyDEBUGBody = {fg = "#4B4E68", bg = "#AFD5DA"},
NotifyDEBUGBorder = {fg = "#AFD5DA", bg = "#AFD5DA"},
NotifyDEBUGTitle = {fg = "#4B4E68", bg = "#AFD5DA", bold = true},
NotifyDEBUGIcon = {link = "NotifyDEBUGTitle"},
NotifyERRORBody = {fg = "#4B4E68", bg = "#E6ADBC"},
NotifyERRORBorder = {fg = "#E6ADBC", bg = "#E6ADBC"},
NotifyERRORTitle = {fg = "#4B4E68", bg = "#E6ADBC", bold = true},
NotifyERRORIcon = {link = "NotifyERRORTitle"},
NotifyINFOBody = {fg = "#4B4E68", bg = "#A8DAF0"},
NotifyINFOBorder = {fg = "#A8DAF0", bg = "#A8DAF0"},
NotifyINFOTitle = {fg = "#4B4E68", bg = "#A8DAF0", bold = true},
NotifyINFOIcon = {link = "NotifyINFOTitle"},
NotifyTRACEBody = {fg = "#4B4E68", bg = "#BCDAB9"},
NotifyTRACEBorder = {fg = "#BCDAB9", bg = "#BCDAB9"},
NotifyTRACETitle = {fg = "#4B4E68", bg = "#BCDAB9", bold = true},
NotifyTRACEIcon = {link = "NotifyTRACETitle"},
NotifyTitle = {fg = "#4B4E68", bg = "#CDD1DB", bold = true},
NotifyIcon = {link = "NotifyTitle"},
NotifyWARNBody = {fg = "#4B4E68", bg = "#E9D3B4"},
NotifyWARNBorder = {fg = "#E9D3B4", bg = "#E9D3B4"},
NotifyWARNTitle = {fg = "#4B4E68", bg = "#E9D3B4", bold = true},
NotifyWARNIcon = {link = "NotifyWARNTitle"},
Number = {fg = "#FE640B"},
Float = {link = "Number"},
["@number"] = {link = "Number"},
Operator = {fg = "#04A7E7"},
["@operator"] = {link = "Operator"},
OverseerCANCELED = {fg = "#7B7E93"},
OverseerNormal = {bg = "#E6E9EF"},
OverseerNormalNC = {link = "OverseerNormal"},
OverseerOutput = {fg = "#4B4E68"},
OverseerPENDING = {fg = "#6C6F84"},
OverseerRUNNING = {fg = "#DD8D1D"},
OverseerTaskBorder = {fg = "#04A7E7"},
Pmenu = {fg = "#7B7E93", bg = "#E6E9EF"},
BlinkCmpMenu = {link = "Pmenu"},
PmenuExtra = {fg = "#9CA0B0"},
BlinkCmpLabelDescription = {link = "PmenuExtra"},
BlinkCmpLabelDetail = {link = "PmenuExtra"},
PmenuExtraSel = {fg = "#9CA0B0", bg = "#BCC0CD", bold = true},
PmenuKind = {},
PmenuKindSel = {},
PmenuMatch = {fg = "#4B4E68", bold = true},
BlinkCmpLabelMatch = {link = "PmenuMatch"},
PmenuMatchSel = {bold = true},
PmenuSbar = {bg = "#CDD1DB"},
PmenuSel = {bg = "#CDD1DB", bold = true},
PmenuThumb = {bg = "#9CA0B0"},
PreInsert = {fg = "#7B7E93"},
ComplMatchIns = {link = "PreInsert"},
PreProc = {fg = "#EA76CB"},
Define = {link = "PreProc"},
DiffviewReflogSelector = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@attribute"] = {link = "PreProc"},
["@attribute.builtin"] = {link = "PreProc"},
Property = {fg = "#7287FD"},
["@property"] = {link = "Property"},
Question = {fg = "#1F66F4"},
ComplHintMore = {link = "Question"},
QuickFixLine = {bg = "#E0E4EB", bold = true},
Rainbow0 = {fg = "#7B7E93"},
Rainbow1 = {fg = "#D20F39"},
markdownH1 = {link = "Rainbow1"},
Rainbow2 = {fg = "#FE640B"},
markdownH2 = {link = "Rainbow2"},
Rainbow3 = {fg = "#DD8D1D"},
markdownH3 = {link = "Rainbow3"},
Rainbow4 = {fg = "#41A12B"},
markdownH4 = {link = "Rainbow4"},
Rainbow5 = {fg = "#20A0B6"},
markdownH5 = {link = "Rainbow5"},
Rainbow6 = {fg = "#7287FD"},
markdownH6 = {link = "Rainbow6"},
Rainbow7 = {fg = "#8839EF"},
markdownH7 = {link = "Rainbow7"},
Repeat = {fg = "#8839EF"},
Search = {fg = "#4B4E68", bg = "#52B7E5"},
SignColumn = {fg = "#BCC0CD"},
SignColumnSB = {fg = "#BCC0CD", bg = "#DDE1E9"},
Special = {fg = "#EA76CB"},
Debug = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
["@punctuation.special"] = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
SpellBad = {sp = "#D20F39", undercurl = true},
SpellCap = {sp = "#DD8D1D", undercurl = true},
SpellLocal = {sp = "#1F66F4", undercurl = true},
SpellRare = {sp = "#41A12B", undercurl = true},
Statement = {fg = "#8839EF"},
StatusLine = {fg = "#9CA0B0", bg = "#E6E9EF"},
StatusLineNC = {fg = "#BCC0CD", bg = "#E6E9EF"},
String = {fg = "#41A12B"},
OverseerField = {link = "String"},
["@string"] = {link = "String"},
["@string.documentation"] = {link = "String"},
["@string.escape"] = {link = "String"},
["@string.regexp"] = {link = "String"},
["@string.special"] = {link = "String"},
["@string.special.path"] = {link = "String"},
["@string.special.symbol"] = {link = "String"},
["@string.special.url"] = {link = "String"},
Substitute = {fg = "#D20F39", bg = "#BCC0CD"},
TabLine = {fg = "#9CA0B0", bg = "#DDE1E9"},
TabLineFill = {bg = "#E6E9EF"},
Tag = {fg = "#7287FD", bold = true},
NeogitTagName = {link = "Tag"},
["@tag"] = {link = "Tag"},
["@tag.attribute"] = {link = "Tag"},
["@tag.builtin"] = {link = "Tag"},
["@tag.delimiter"] = {link = "Tag"},
TelescopeMatching = {fg = "#1F66F4"},
TelescopePreviewBorder = {fg = "#E6E9EF", bg = "#DDE1E9"},
TelescopePreviewNormal = {fg = "#4B4E68", bg = "#DDE1E9"},
TelescopePreviewTitle = {fg = "#4B4E68", bg = "#DDE1E9", bold = true},
TelescopePromptBorder = {fg = "#E6E9EF", bg = "#EFF1F5"},
TelescopePromptNormal = {fg = "#4B4E68", bg = "#EFF1F5"},
TelescopePromptPrefix = {fg = "#DD7878"},
TelescopePromptTitle = {fg = "#4B4E68", bg = "#EFF1F5", bold = true},
TelescopeResultsBorder = {fg = "#E6E9EF", bg = "#E6E9EF"},
TelescopeResultsNormal = {fg = "#4B4E68", bg = "#E6E9EF"},
TelescopeResultsTitle = {fg = "#4B4E68", bg = "#E6E9EF", bold = true},
TelescopeSelection = {fg = "#DD7878", bg = "#CAD0DD", bold = true},
TelescopeSelectionCaret = {fg = "#DD7878", bg = "#CAD0DD"},
TermCursorNC = {link = "TermCursor"},
Title = {fg = "#1F66F4"},
MarkviewTableHeader = {link = "Title"},
NeogitDiffHeader = {link = "Title"},
NeogitHunkHeader = {link = "Title"},
Todo = {fg = "#EFF1F5", bg = "#DD7878"},
Type = {fg = "#DD8D1D"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@type"] = {link = "Type"},
["@type.builtin"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {underline = true},
Variable = {fg = "#4B4E68"},
["@variable"] = {link = "Variable"},
["@variable.builtin"] = {link = "Variable"},
["@variable.member"] = {link = "Variable"},
["@variable.parameter"] = {link = "Variable"},
["@variable.parameter.builtin"] = {link = "Variable"},
VertSplit = {fg = "#DDE1E9"},
Visual = {bg = "#BCC0CD", bold = true},
VisualNOS = {link = "Visual"},
WarningMsg = {fg = "#DD8D1D"},
WhichKeyDesc = {fg = "#EA76CB"},
WhichKeyGroup = {fg = "#1F66F4"},
WhichKeySeparator = {fg = "#9CA0B0"},
WhichKeyValue = {fg = "#9CA0B0"},
Whitespace = {fg = "#BCC0CD"},
WildMenu = {bg = "#9CA0B0"},
WinBar = {fg = "#DC8B79"},
NeogitSectionHeader = {link = "WinBar"},
WinBarNC = {link = "WinBar"},
Winseparator = {fg = "#DDE1E9", bg = "none"},
DiffviewWinSeparator = {link = "Winseparator"},
MsgSeparator = {link = "Winseparator"},
NeogitWinSeparator = {link = "Winseparator"},
["lualine_a_command"] = {fg = "#EFF1F5", bg = "#FE640B", bold = true},
["lualine_a_inactive"] = {fg = "#1F66F4", bg = "none"},
["lualine_a_insert"] = {fg = "#EFF1F5", bg = "#41A12B", bold = true},
["lualine_a_normal"] = {fg = "#E6E9EF", bg = "#1F66F4", bold = true},
["lualine_a_replace"] = {fg = "#EFF1F5", bg = "#D20F39", bold = true},
["lualine_a_terminal"] = {fg = "#EFF1F5", bg = "#41A12B", bold = true},
["lualine_a_visual"] = {fg = "#EFF1F5", bg = "#8839EF", bold = true},
["lualine_b_command"] = {fg = "#FE640B", bg = "#CDD1DB"},
["lualine_b_inactive"] = {fg = "#BCC0CD", bg = "none", bold = true},
["lualine_b_insert"] = {fg = "#41A12B", bg = "#CDD1DB"},
["lualine_b_normal"] = {fg = "#1F66F4", bg = "#CDD1DB"},
["lualine_b_replace"] = {fg = "#D20F39", bg = "#CDD1DB"},
["lualine_b_terminal"] = {fg = "#41A12B", bg = "#CDD1DB"},
["lualine_b_visual"] = {fg = "#8839EF", bg = "#CDD1DB"},
["lualine_c_command"] = {bg = "none"},
["lualine_c_inactive"] = {fg = "#9CA0B0", bg = "none"},
["lualine_c_insert"] = {bg = "none"},
["lualine_c_normal"] = {fg = "#4B4E68", bg = "none"},
["lualine_c_replace"] = {bg = "none"},
["lualine_c_terminal"] = {bg = "none"},
["lualine_c_visual"] = {bg = "none"},
["@markup.heading"] = {link = "markdownH1"},
["@markup.heading.1"] = {link = "markdownH2"},
["@markup.heading.2"] = {link = "markdownH3"},
["@markup.heading.3"] = {link = "markdownH4"},
["@markup.heading.4"] = {link = "markdownH5"},
["@markup.heading.5"] = {link = "markdownH6"},
["@markup.heading.6"] = {link = "markdownH7"},
["@markup.italic"] = {italic = true},
["@markup.link"] = {fg = "#7287FD"},
["@markup.link.url"] = {fg = "#7287FD", underline = true},
["@markup.link.label"] = {link = "@markup.link"},
["@markup.list"] = {fg = "#41A12B"},
["@markup.list.unchecked"] = {fg = "#8C8FA1"},
["@markup.list.checked"] = {link = "@markup.list"},
["@markup.math"] = {fg = "#1F66F4"},
["@markup.quote"] = {fg = "#EA76CB"},
["@markup.raw"] = {fg = "#41A12B"},
["@markup.raw.block"] = {link = "@markup.raw"},
["@markup.strikethrough"] = {strikethrough = true},
["@markup.strong"] = {bold = true},
["@markup.underline"] = {underline = true},
-- PATCH_CLOSE
}

vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='catppuccin'")

for group, attrs in pairs(colors) do
    vim.api.nvim_set_hl(0, group, attrs)
end

vim.g.lualine_theme = {
    normal = {
        a = colors["lualine_a_normal"],
        b = colors["lualine_b_normal"],
        c = colors["lualine_c_normal"],
    },
    insert = {
        a = colors["lualine_a_insert"],
        b = colors["lualine_b_insert"],
        c = colors["lualine_c_insert"],
    },
    replace = {
        a = colors["lualine_a_replace"],
        b = colors["lualine_b_replace"],
        c = colors["lualine_c_replace"],
    },
    visual = {
        a = colors["lualine_a_visual"],
        b = colors["lualine_b_visual"],
        c = colors["lualine_c_visual"],
    },
    command = {
        a = colors["lualine_a_command"],
        b = colors["lualine_b_command"],
        c = colors["lualine_c_command"],
    },
    inactive = {
        a = colors["lualine_a_inactive"],
        b = colors["lualine_b_inactive"],
        c = colors["lualine_c_inactive"],
    },
}


